services:
  server-app:
    pull_policy: never
    build:
      context: .
    environment:
      - TARGET=server
    ports:
      - "4403:4403"
    image: so2-app:latest 
  client-app:
    pull_policy: never
    build:
      context: .
    environment:
      - TARGET=client
    image: so2-app:latest
    network_mode: "host"
