services:
  server-app:
    pull_policy: never
    build:
      context: .
    environment:
      - TARGET=server
    image: so2-app:latest 
  client-app:
    pull_policy: never
    build:
      context: .
    environment:
      - TARGET=client
    image: so2-app:latest
