services:
  server-app:
    pull_policy: never
    build:
      context: .
    environment:
      - TARGET=server
    ports:
      - "4403:4403"
    image: so2-app:latest 
  client-app:
    pull_policy: never
    build:
      context: .
    environment:
      - TARGET=client
    image: so2-app:latest
    # It is easier for the client app to connect
    # to the server using the 127.0.0.1 IP. And for
    # that we need the client to have host network access.
    network_mode: "host"
